//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionAlarm.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MotionAlarm.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion detected! Alarm is active..
        /// </summary>
        internal static string Alarm_AlarmActive {
            get {
                return ResourceManager.GetString("Alarm_AlarmActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion detected! Alarm is about to sound..
        /// </summary>
        internal static string Alarm_AlarmCountdown {
            get {
                return ResourceManager.GetString("Alarm_AlarmCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion detected!.
        /// </summary>
        internal static string Alarm_MotionDetected {
            get {
                return ResourceManager.GetString("Alarm_MotionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security is enabled.
        /// </summary>
        internal static string Alarm_Status_Armed {
            get {
                return ResourceManager.GetString("Alarm_Status_Armed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security is disabled.
        /// </summary>
        internal static string Alarm_Status_Disarmed {
            get {
                return ResourceManager.GetString("Alarm_Status_Disarmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of detected motion.
        /// </summary>
        internal static string AlarmLog_Description {
            get {
                return ResourceManager.GetString("AlarmLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No alarm events have been recorded yet..
        /// </summary>
        internal static string AlarmLog_Empty_Description {
            get {
                return ResourceManager.GetString("AlarmLog_Empty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History is empty.
        /// </summary>
        internal static string AlarmLog_Empty_Title {
            get {
                return ResourceManager.GetString("AlarmLog_Empty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more.
        /// </summary>
        internal static string AlarmLog_LoadMore {
            get {
                return ResourceManager.GetString("AlarmLog_LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity: {0}.
        /// </summary>
        internal static string AlarmLog_Sensitivity {
            get {
                return ResourceManager.GetString("AlarmLog_Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siren: Disabled.
        /// </summary>
        internal static string AlarmLog_SirenDisabled {
            get {
                return ResourceManager.GetString("AlarmLog_SirenDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siren: Enabled.
        /// </summary>
        internal static string AlarmLog_SirenEnabled {
            get {
                return ResourceManager.GetString("AlarmLog_SirenEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Log.
        /// </summary>
        internal static string AlarmLog_Title {
            get {
                return ResourceManager.GetString("AlarmLog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers today: {0}.
        /// </summary>
        internal static string AlarmLog_TodayCount {
            get {
                return ResourceManager.GetString("AlarmLog_TodayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string Common_Seconds {
            get {
                return ResourceManager.GetString("Common_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISARM.
        /// </summary>
        internal static string Home_Alarm_Disable {
            get {
                return ResourceManager.GetString("Home_Alarm_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM.
        /// </summary>
        internal static string Home_Alarm_Enable {
            get {
                return ResourceManager.GetString("Home_Alarm_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE WAIT.
        /// </summary>
        internal static string Home_Alarm_Wait {
            get {
                return ResourceManager.GetString("Home_Alarm_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security will be enabled.
        /// </summary>
        internal static string Home_ArmingSoon {
            get {
                return ResourceManager.GetString("Home_ArmingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start monitoring service..
        /// </summary>
        internal static string Home_MonitoringStartFailed {
            get {
                return ResourceManager.GetString("Home_MonitoringStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification permission was not granted. Monitoring cannot be started..
        /// </summary>
        internal static string Home_NotificationPermissionDenied {
            get {
                return ResourceManager.GetString("Home_NotificationPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion protection is active.
        /// </summary>
        internal static string Notification_MotionProtectionActive {
            get {
                return ResourceManager.GetString("Notification_MotionProtectionActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time before the alarm is armed after pressing the button..
        /// </summary>
        internal static string Settings_ArmDelay_Description {
            get {
                return ResourceManager.GetString("Settings_ArmDelay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arming Delay.
        /// </summary>
        internal static string Settings_ArmDelay_Title {
            get {
                return ResourceManager.GetString("Settings_ArmDelay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure alarm operation.
        /// </summary>
        internal static string Settings_Description {
            get {
                return ResourceManager.GetString("Settings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        internal static string Settings_Saved {
            get {
                return ResourceManager.GetString("Settings_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A higher level means greater sensitivity to motion..
        /// </summary>
        internal static string Settings_Sensitivity_Description {
            get {
                return ResourceManager.GetString("Settings_Sensitivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Sensitivity.
        /// </summary>
        internal static string Settings_Sensitivity_Title {
            get {
                return ResourceManager.GetString("Settings_Sensitivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the siren when an alarm is triggered.
        /// </summary>
        internal static string Settings_Siren_Description {
            get {
                return ResourceManager.GetString("Settings_Siren_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audible Alarm.
        /// </summary>
        internal static string Settings_Siren_Title {
            get {
                return ResourceManager.GetString("Settings_Siren_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time from motion detection until the siren sounds..
        /// </summary>
        internal static string Settings_SoundDelay_Description {
            get {
                return ResourceManager.GetString("Settings_SoundDelay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Delay.
        /// </summary>
        internal static string Settings_SoundDelay_Title {
            get {
                return ResourceManager.GetString("Settings_SoundDelay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
    }
}
